csmrd-init: Add functions to open/close, send/recv on mhi channels
Add functions for basic usage of mhi channels in mksh

Change-Id: Ibd7ba69f60c44c6e0015c5c2f3b8e4903e5b3f3e

diff --git a/recipes-products/images/include/csmrd-init b/recipes-products/images/include/csmrd-init
--- a/recipes-products/images/include/csmrd-init
+++ b/recipes-products/images/include/csmrd-init
@@ -187,6 +187,182 @@ start_rdshell()
     exec /bin/mksh
 }
 
+# ctrl_msg_send - Send a string over an mhi channel
+# @FILE:  file descriptor of an open mhi channel
+# @MSG: message to send
+#
+# Returns 0 on success
+mhi_ch_sendmsg() {
+    local MHI_CH="$1"
+    shift 1
+    local MSG="$*"
+    local ch_fd=$(get_mhi_ch_fd $MHI_CH)
+
+    if [ -z "$ch_fd" ]; then
+        echo "MHI channel $MHI_CH is not open" >&2
+        return 1
+    fi
+
+    eval "echo $MSG >&$ch_fd"
+    ret="$?"
+    if [ "$ret" -ne 0 ]; then
+        echo "Failed to send on $MHI_CH" >&2
+    fi
+
+    return $ret
+}
+
+MHI_RECV_TIMEOUT=10
+# mhi_ch_recvmsg - Receive a single string over an mhi channel
+# @MHI_CH:  Path to mhi channel
+# @TIMEOUT: (optional) Seconds to receive message in seconds; default MHI_RECV_TIMEOUT
+#
+# Return 0 if messages was receieved
+# If received, received message is printed
+mhi_ch_recvmsg() {
+    local MHI_CH="$1"
+    local TIMEOUT="$2"
+    local ch_fd=$(get_mhi_ch_fd $MHI_CH)
+
+    if [ -z "$ch_fd" ]; then
+        echo "MHI channel $MHI_CH is not open" >&2
+        return 1
+    fi
+
+    local ctrl_fd="${READ_FD[$ch_fd]}"
+    if [ -z "$ctrl_fd" ]; then
+        echo "Read file desc is not open" >&2
+        return 1
+    fi
+
+    if [ -z "$TIMEOUT" ]; then
+        TIMEOUT="$MHI_RECV_TIMEOUT"
+    fi
+
+    IFS= read -u$ctrl_fd -t $TIMEOUT -r line
+    ret="$?"
+    if [ "$ret" -ne 0 ]; then
+        echo "Failed to receive on $MHI_CH" >&2
+        return $ret
+    fi
+
+    echo $line
+
+    return $ret
+}
+
+# get_mhi_ch_fd - Find an file descriptor associated with an mhi channel
+# @MHI_CH: Path to mhi channel
+#
+# Returns 0 if a file descriptor was found
+# If found, assigned file descriptor for MHI_CH is printed
+get_mhi_ch_fd() {
+    local MHI_CH="$1"
+
+    for i in ${!MHI_CH_FD[@]}; do
+        if [ "${MHI_CH_FD[$i]}" = "$MHI_CH" ]; then
+            echo $i
+            return 0
+        fi
+    done
+
+    for open_fd in $(ls -d /proc/$$/fd/*); do
+        open_file="$(readlink $open_fd)"
+        if [ "$open_file" = "$MHI_CH" ]; then
+            ch_fd=$(basename $open_fd)
+            echo "$ch_fd"
+            return 0
+        fi
+    done
+    return 1
+}
+
+# get_new_fd - Locates and prints a new file descriptor
+get_new_fd() {
+    local ch_fd=0
+    while [ -e "/proc/$$/fd/$ch_fd" ]; do
+        (( ch_fd += 1 ))
+    done
+    echo $ch_fd
+}
+
+# mhi_ch_open - Open an mhi channel as read/write
+# @MHI_CH: Path to mhi channel
+#
+# Returns 0 if MHI_CH was successfully opened
+mhi_ch_open() {
+    local MHI_CH="$1"
+    local ch_fd=0
+
+    if [ ! -e "$MHI_CH" ]; then
+        return 1
+    fi
+
+    ch_fd="$(get_mhi_ch_fd $MHI_CH)"
+    if [ ! -z "$ch_fd" ]; then
+        return 0
+    fi
+
+    ch_fd=$(get_new_fd)
+    eval "exec $ch_fd<>$MHI_CH" 2>/dev/null
+    ret="$?"
+    if [ "$ret" -ne 0 ]; then
+        echo "Could not open $MHI_CH" >&2
+        return $ret
+    fi
+
+    cat - <&"$ch_fd" |&
+    READ_PID[$ch_fd]="$!"
+
+    ch_rfd=$(get_new_fd)
+    eval "exec $ch_rfd<&p" 2>/dev/null
+    ret="$?"
+    if [ "$ret" -ne 0 ]; then
+        echo "Error opening read process" >&2
+        return $ret
+    fi
+    READ_FD[$ch_fd]="$ch_rfd"
+
+    echo "Opened $MHI_CH" >&2
+    MHI_CH_FD[$ch_fd]="$MHI_CH"
+    return 0
+}
+
+# mhi_ch_close - Close an open mhi channel
+# @MHI_CH: Path to mhi channel
+#
+# Returns 0 if file descriptor was able to close
+mhi_ch_close() {
+    local MHI_CH="$1"
+    local ch_fd=$(get_mhi_ch_fd $MHI_CH)
+
+    if [ -z "$ch_fd" ]; then
+        echo "MHI channel $MHI_CH is not open" >&2
+        return 1
+    fi
+
+    if [ ! -z "${READ_PID[$ch_fd]}" ]; then
+        kill "${READ_PID[$ch_fd]}"
+        READ_PID[$ch_fd]=""
+    fi
+
+    if [ ! -z "${READ_FD[$ch_fd]}" ]; then
+        eval "exec ${READ_FD[$ch_fd]}>&-"
+        READ_FD[$ch_fd]=""
+    fi
+
+    eval "exec $ch_fd>&-"
+    ret="$?"
+    if [ "$ret" -ne 0 ]; then
+        echo "Could not close <$ch_fd>" >&2
+        return $ret
+    fi
+    echo "Closed $MHI_CH" >&2
+
+    MHI_CH_FD[$ch_fd]=""
+    return 0
+}
+
 config_interface()
 {
     LOCAL_INTERFACE="$1"
